-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE usuarios (
id_user SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nivel SMALLINT NOT NULL,
nome VARCHAR(30) NOT NULL,
e_mail VARCHAR(35) NOT NULL,
senha VARCHAR(30) NOT NULL
)

CREATE TABLE reservas (
id_reservas SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_user SMALLINT NOT NULL,
id_curso SMALLINT NOT NULL,
id_ambiente SMALLINT NOT NULL,
hora TIME NOT NULL,
hora_relogio TIME NOT NULL,
data DATE NOT NULL,
FOREIGN KEY(id_user) REFERENCES usuarios (id_user) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE cursos (
id_curso SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_user SMALLINT NOT NULL,
nome VARCHAR(15) NOT NULL,
periodo VARCHAR(8) NOT NULL,
tipo_hora TIME NOT NULL,
predio VARCHAR(15) NOT NULL,
FOREIGN KEY(id_user) REFERENCES usuarios (id_user) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE ambientes (
id_ambiente SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(15) NOT NULL
)

ALTER TABLE reservas ADD FOREIGN KEY(id_curso) REFERENCES cursos (id_curso) ON UPDATE CASCADE ON DELETE RESTRICT
ALTER TABLE reservas ADD FOREIGN KEY(id_ambiente) REFERENCES ambientes (id_ambiente) ON UPDATE CASCADE ON DELETE RESTRICT
